In [1]:
import numpy as np

#Numpy is usually imported under the `np` alias.
#in Python alias are an alternate name for referring to the same thing.
#We create an alias with the `as` keyword while importing.

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# Checking Numpy Version.

The version string is stored under `__version__` attribute.

In [6]:
print(np.__version__)

1.23.5


# Numpy Creating Arrays

# # Create a Numpy ndarray Object

Numpy is ussed to work with arrays.

The array object in numpy is called `ndarray`.

We can create a Numpy `ndarray` object by using the `array()` function.

In [8]:
print(type(arr))
#`type(): This built-in Python function tells us the type of object passed to it.
#Like the above code it shows that `arr` is `numpy.ndarray` type.

<class 'numpy.ndarray'>


To create an `ndarray`, we can pass a list, tuple, or any array-like object into the`array()` method, and it will be converted into an `ndarray`:

In [9]:
#Use a tuple to create a Numpy array:

arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

[1 2 3 4 5]


# Dimensions in Arrays.

A dimension in arrays is one level of array depth(nested arrays).

**Nested array:** are arrays that have arrays as their elements.

# 0-D Arrays

0-D arrays, or Scalars, are the elements in array. Each value in an array is a 0-D array.

In [11]:
#Creating a 0-\d array with value 42.
arr2 = np.array(42)

print(arr2)

42


# 1-D Arrays

An array that has 0-D array as irs element is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [12]:
#Creating a 1-D array containing the value 1,2,3,4,5:

arr3 = np.array([1, 2, 3, 4, 5])

print(arr3)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-d arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

**Note:
Numpy has a whole sub module dedicated towards matrix operations called `numpy.mat`**

In [13]:
#Create a 2-D array containing two arrays with the values 1,2,3, and 4,5,6:

arr4 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr4)

[[1 2 3]
 [4 5 6]]


# 3-D Arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D arrays.

These are often used to represent a 3rd order tensor.

In [15]:
#Create a 3-D array with 2-D arrays,
#both containing two arrays with the values 1,2,3 and 4,5,6:

arr5 = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]])

print(arr5)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

Numpy Arrays provides the `ndim` attribute that returns an interger that tells us how many dimensions the array have.

In [17]:
#Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

An array can have any number of dimensions.

When an array is created, you can define the number of dimensions by using the `ndmin` argument

In [19]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

arr6 = np.array([1, 2, 3, 4], ndmin=5)

print(arr6)
print("number of dimensions :", arr6.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In the above array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

# NumPy Array Indexing


# 1. Access array Elements.

Array indexing is the same as accessing an array element.

You can access an array element by reffering to its index number.

The indexes in NumPy array start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [4]:
# Get the first element from the following array.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])    # Getting the second element from the array.

# Get the 3rd and the 4th elements from the above array and add them

print(arr[2] + arr[3])

1
2
7


# Access 2 - D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [6]:
# Access the element on the first row, second column.

list = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('2nd element on 1st row: ', list[0, 1])

# Access element on the 2nd row, 5th column.

print('5th element on 2nd row: ', list[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


# Accessing 3-D Arrays

To access elements from 3-D arrays we can use comma separated intergers representing the dimensions and the index of the element.

In [8]:
# Access the 3rd element of the 2nd array of the first array.

list1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(list1[0, 1, 2])

6


# Example Explained.

`arr[0, 1, 2]` prints the value `6`.

And this is why:

The first number represents the first dimension, which contains two arrays:

`[[1, 2, 3], [4, 5, 6]]`

and:

`[[7, 8, 9], [10, 11, 12]]`

Since we selected 0, we are left with the first array:

`[[1, 2, 3], [4, 5, 6]]`

The second number represents the second dimension, which also contains two arrays:

`[1, 2, 3]`

and:

`[4, 5, 6]`

Since we selected 1, we are left with the second array:

`[4, 5, 6]`

The third number represents the third dimension, which contains three values:

`4`
`5`
`6`
Since we selected 2, we end up with the third value:

`6`



# Negative Indexing.

Use negative to access an array from the end.

In [2]:
# Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Numpy Array Slicing.

# Slicing arrays

Slicing in Python means takking elements from one given index to another given index.

We pass slice instead of index like this: *`[start:end]`*.

We can also define the step, like this: *`[start:end:step]`*.
    
If we do not pass start it is considered `0`

If we do not pass end it is considered length of array in that dimension.

If we do not pass step it is considered `1`

In [3]:
# Slice elements from index 1 to index 5 from the following array:

arR = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[[ 6  7  8  9 10]]


**NOTE:**
    
   The results *includes* the start index, but *excludes* the end index. 

In [5]:
# Slice elements from index 4 to the end of the array:

arR1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arR1[4:])

[5 6 7]


In [6]:
# Slice elements from the begining to index 4 (not included):

arR2 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arR2[:4])

[1 2 3 4]


# Negative Slicing.

Use the minus operator to refer to an index from the end:

In [7]:
# Slice from the index 3 from the end to index 1 from the end;

arR3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arR3[-3:-1])

[5 6]


# STEP.

Use the `step` value to determine the step of the slicing:

In [9]:
# Return every other elment from index 1 to index 5:

arR4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arR4[1:5:2])

# Return every other element from the entire array:

print(arR4[::2])

[2 4]
[1 3 5 7]


# Slicing 2-D Arrays

In [10]:
# From the 2nd element, slice elements from inddex 1 to index 4 (not included):

arR5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arR5[1, 1:4])

[7 8 9]


**NOTE:**
   Remember that 2nd element has index 1.

In [11]:
# From both elements, return index 2:

print(arR5[0:2,2])

[3 8]


In [12]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

print(arR5[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types.

# Data Types in Python.

By default Python have these data types:
    
   - `strings` - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    
   - `integer` - used to represent integer numbers. e.g. -1, -2, -3
   
   - `float` - used to represent real numbers. e.g. 1.2, 42.42
   
   -`boolean` - used to represent `True` or `False`.
   
   -`complex` - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy.

NumPy has some extra data types, and refer to data types with character,
like `i` for integers, `u` for unsigned integers etc.


Below is a list of all data types in NumPy and the characters used to represent them

- `i` - integer

- `b` - boolean

- `u` - unsigned integer

- `f` - float

- `c` - complex float

- `m` - timedelta

- `M` - datetime

- `O` - object

- `S` - string

- `U` - unicode string

- `V` - fixed chunk of memory for other type (void)


# Checking the Data Type of an Array

The NumPy array object has a property called `dtype` that returns the data type of the array:

In [17]:
# Get the data type of an array object:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


# Get the data type of an array containing strings:

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

int32
<U6


# Creating Arrays With a Defined Data Type.

We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements:

In [18]:
# Create an array with data type string:

arrs =  np.array([1, 2, 3, 4], dtype='S')

print(arrs)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
<U6


For `i`, `u`,`f`, `S` and `U` we can define size as well.

In [22]:
# Create an array with data type 4 bytes integer:

arri = np.array([1, 2, 3, 4], dtype='i4')

print(arri)
print(arri.dtype)

[1 2 3 4]
int32


# What if a Value Can Not Be Converted?

If a type is given which elements can not be casted then NumPy will raise a ValueError.

**ValueError:** In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [23]:
# An non integer string like 'a' can not be converted to integer (will raise an error):

arry = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

The best way to change thee data type of an existing array, is to make a copy of the array with the `astype()` method.

The `astype()` function creates a copy of the array, and allows you to specify the data tyoe as a parameter.

The data type can be specified using a string, like `f`for float, `i` for integer etc. or you can use the data type directly like `float` for float and `int` for integer.

In [26]:
#Change data type from float to integer by using `i` as parameter value:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [27]:
# Change data type from float to integer by using `int` as parameter value:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [28]:
# Change data type from integer to boolean:

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
